services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - "8123:8123"
    volumes:
      - ./ha/configuration.yaml:/config/configuration.yaml:ro
      - ./ha/automations.yaml:/config/automations.yaml:ro
      - ./ha/scenes.yaml:/config/scenes.yaml:ro
      - ./ha/scripts.yaml:/config/scripts.yaml:ro
      - ./ha/secrets.yaml:/config/secrets.yaml:ro
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    networks:
      - homeassistant_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8123"]
      interval: 45s
      timeout: 30s
      retries: 3
    depends_on:
      mosquitto:
        condition: service_healthy
    restart: unless-stopped
    privileged: true
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - homeassistant_network
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "docker_healthcheck", "-W", "3"]
      interval: 30s
      timeout: 10s
      retries: 3
  ecowitt2mqtt:
    image: bachya/ecowitt2mqtt
    restart: unless-stopped
    ports:
      - 4199:4199/udp
    networks:
      - homeassistant_network
    environment:
      - ECOWITT2MQTT_PORT=4199
      - ECOWITT2MQTT_MQTT_BROKER=mosquitto
      - ECOWITT2MQTT_MQTT_PORT=1883
      - ECOWITT2MQTT_MQTT_TOPIC=weather/sainlogic
      - ECOWITT2MQTT_HASS_DISCOVERY=true
    depends_on:
      mosquitto:
        condition: service_healthy
  influxdb:
    image: influxdb:latest
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - "8086:8086"
    networks:
      - homeassistant_network
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    healthcheck:
      test: "influx ping || exit 1"
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 20s
    depends_on:
      homeassistant:
        condition: service_healthy
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
    ports:
      - "3000:3000"
    networks:
      - homeassistant_network
    depends_on:
      influxdb:
        condition: service_healthy
  weather_emulator:
    build: ./weather_emulator
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_TOPIC=weather/sainlogic
      - TEMP_MIN=-5
      - TEMP_MAX=35
      - UPDATE_FREQUENCY=15
    networks:
      - homeassistant_network
    depends_on:
      homeassistant:
        condition: service_healthy
networks:
  homeassistant_network:
    driver: bridge
