
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# MQTT integration
mqtt:
  broker: mosquitto
  port: 1883

# InfluxDB integration
influxdb:
  host: influxdb
  port: 8086
  database: my-bucket
  username: my-user
  password: e7l5cYbO6mk21qrMsCHXW2WlTXkW3okhB8znZSdzG_e015Wu6yARslCsnZ-MJara_2PkYaQYpuEcoAPVLy9IKA==
  verify_ssl: false
  max_retries: 3
  default_measurement: state